version: "3.8"

networks:
  pong_bridge:
    name: pong_bridge
    driver: bridge

services:
  database:
    container_name: pong_database
    hostname: pong_db_host
    image : postgres:latest
    init : true
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWOR: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - pong_bridge

  backend:
    container_name: pong_backend
    hostname: pong_be_host
    build: ./src/backend
    init: true
    env_file:
      - .env
    volumes:
      - ./src/vol/back:/pong
    networks:
      - pong_bridge
    ports:
      - 3000:3000

 
  frontend:
    container_name: pong_frontend
    hostname: pong_fe_host
    build: ./src/frontend
    init: true
    environment:
      VITE_AWS_URL: ${BACKEND_URL}
      VITE_AWS_PORT: ${BACKEND_PORT}
      VITE_CLIENT_ID: ${CLIENT_ID}
      VITE_CLIENT_SECRET: ${CLIENT_SECRET}
      VITE_REDIRECT_URI: ${REDIRECT_URI}
    volumes:
      - ./src/vol/front:/pong
    networks:
      - pong_bridge
    ports:
      - 4242:4242

