version: "3.8"

networks:
  ft_bridge:
    name: ft_bridge
    driver: bridge

services:

  database:
    container_name: pong_DB
    hostname: database
    image: postgres:latest
    init: true
    env_file:
      - .env
    networks:
      - ft_bridge
    ports:
      - 5432

  backend:
    container_name: pong_BE
    hostname: backend
    depends_on:
      - database
    build: ./back
    init: true
    networks:
      - ft_bridge
    ports:
      - 4223:22
      - 3000:3000
    volumes:
      - ./vol/back:/root/back
    #------------------
    tty: true
    stdin_open: true


  frontend:
    container_name: pong_FE
    hostname: frontend
    depends_on:
      - backend
    build: ./front
    init: true
    networks:
      - ft_bridge
    ports:
      - 4222:22
      - 5173:5173
    volumes:
      - ./vol/front:/root/front
    #------------------
    tty: true
    stdin_open: true

