version: "3.8" 

services:
  frontend:
    container_name: front
    hostname: front
    networks:
      - pong_net
    build: ./frontend
    image: front:v1
    init: true
    tty: true
    stdin_open: true
    volumes:
      - ./volume/front:/root/front
    ports:
      - 4222:22
      - 3000:3000
  backend:
    container_name: back
    hostname: back
    networks:
      - pong_net
    image: back:v1
    build: ./backend
    init: true
    tty: true
    stdin_open: true
    volumes:
      - ./volume/back:/root/back
    ports:
      - 4223:22
      - 3001:3001

networks:
  pong_net:
    name : pong_net
    driver: bridge
