version: "3.8" 

services:
  base_cont:
    container_name: base_cont
    build: .
    image: ubuntu:node_base
  frontend:
    container_name: front
    hostname: front
    build: ./frontend
    image: front:v1
    init: true
    tty: true
    stdin_open: true
    depends_on:
      - base_cont
    volumes:
      - ./volume/front:/root/front
    ports:
      - 4222:22
      - 3000:3000
  backend:
    container_name: back
    hostname: back
    image: back:v1
    build: ./backend
    init: true
    tty: true
    stdin_open: true
    depends_on:
      - base_cont
    volumes:
      - ./volume/back:/root/back
    ports:
      - 4223:22

  
